[package]
name = "api-tpl-rs"
version = "1.2.0"
edition = "2021"
description = "API project template for Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "api", "cmd", "entity", "library"]

[dependencies]
tokio = { version = "1", features = ["full"] }

# workspace modules
api = { path = "api" }
cmd = { path = "cmd" }
library = { path = "library" }
